#!/bin/bash

source pull-dependencies.lib

ensure_dir lib

# CoreNLP (Stanford's NLP package)
cd lib;
  gitClone git@github.com:stanfordnlp/CoreNLP.git
  cd CoreNLP;
    ant jar;
  cd ..;
cd .

# JUnit (for test cases)
download lib http://central.maven.org/maven2/junit/junit/4.11/junit-4.11.jar

# Hamcrest (for test cases)
download lib http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-junit/2.0.0.0/hamcrest-junit-2.0.0.0.jar
download lib http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
