# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 23:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0022_auto_20160318_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericPerspectiveRatingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expressions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='linked numeric expressions', size=None)),
                ('perspectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Actual perspective', size=None)),
                ('systems', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='System that generated the perspective', size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Score assigned by system', size=None)),
                ('mention', models.ForeignKey(help_text='linked numeric mention', on_delete=django.db.models.deletion.CASCADE, related_name='perspective_rating_tasks', to='cc.NumericMention')),
            ],
        ),
        migrations.CreateModel(
            name='NumericPerspectiveRatingTaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField(help_text="Which system's response was best. ('-1' for none)")),
                ('assignment_id', models.CharField(max_length=1024)),
                ('worker_id', models.CharField(max_length=1024)),
                ('worker_time', models.DurationField()),
                ('approval', models.BooleanField(default=True)),
                ('inspected', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('task', models.ForeignKey(help_text='Pointer to perspective rating task', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cc.NumericPerspectiveRatingTask')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='numericperspectiveratingtaskresponse',
            unique_together=set([('assignment_id', 'task')]),
        ),
    ]
