# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0023_auto_20160530_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericperspectiveratingtaskresponse',
            name='error_analysis',
            field=models.TextField(default=''),
        ),
    ]
