# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0024_numericperspectiveratingtaskresponse_error_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numericperspectiveratingtaskresponse',
            name='error_analysis',
        ),
        migrations.AddField(
            model_name='numericperspectiveratingtask',
            name='error_analysis',
            field=models.TextField(default=''),
        ),
    ]
